{{- if not .Values.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-pro.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  redisPass: "{{ .Values.redis.pass }}"
  mongoURL: {{ include "tyk-pro.mongo_url" . | quote }}
  pgConnectionString: {{ include "tyk-pro.pg_connection_string" . }}
  dashboard-admin-api-secret: "{{ .Values.secrets.AdminSecret }}"
  dashboard-admin-password: "12345"
  node-secret: "{{ .Values.secrets.APISecret }}"
  gateway-api-secret: "{{ .Values.secrets.APISecret }}"
  DashLicense: "{{ .Values.dash.license }}"
  EnterprisePortalLicense: "{{ .Values.enterprisePortal.license }}"
  EnterprisePortalAdminPassword: "{{ .Values.enterprisePortal.adminUser.password }}"
  EnterprisePortalStorgeConnectionString: "{{ .Values.enterprisePortal.storage.database.connectionString }}"
  MDCBLicense: "{{ .Values.mdcb.license }}"
  tibSecret: "{{ .Values.tib.secret }}"
{{- end }}
